### PR TITLE
hw9 first commit

### PR DESCRIPTION
**Pull request by MaryanaKravets**
Please, check my homework!

### CODE REVIEW

**Review by BogdanShulga — COMMENTED** [review]
1. code works nice as expected, you use streams very good, as for me
2. statement lambda can be replaced with expression lambda - it's idea said not me in  myfunctionalinterface/Main.class :)
3. class Protector (not Protected) must have one private field Thing thing according to task :|

**Review by NazarBondarenkoQ — APPROVED** [review]
Code works as expected an ready to move further after adding remarks mentioned by Bogdan. Good and important: all is written accroding to the convention demands. Approved.

**Review by BogdanShulga — APPROVED** [review]
I'm satisfied.

**Comment by MaryanaKravets** [comment]
Bogdan, I added your remarks.

**Review by NickRbk — APPROVED** [review]
If in lamda there is only one parameter and you don't write its type you can skip parenthesis.

**Comment by MaryanaKravets** [comment]
NickRbk, I skiped parenthesis.

**Pull request merged**
